[[redirects]]
    from = "/"
    to = "/index.html"
    status = 200
    force = false

[[redirects]]
    from = "/index.html/scoreboard"
    to = "/index.html/scoreboard/admin"
    status = 301
    force = false