import React, {useEffect, useState} from 'react';
import PlayerCard from '../components/OverallPlayerCard';
import { GoogleSpreadsheet } from 'google-spreadsheet';
import { Table } from 'semantic-ui-react';

function openNetlifyModal() {
  const netlifyIdentity = window.netlifyIdentity;

  if(netlifyIdentity) {
    netlifyIdentity.open();
  } else {
    console.log('netlifyIdentity not defined')
  }
}

const {REACT_APP_SHEET_ID} = process.env;
const {REACT_APP_GOOGLE_CLIENT_EMAIL} = process.env;
const {REACT_APP_GOOGLE_PRIVATE_KEY} = process.env;

const doc = new GoogleSpreadsheet(REACT_APP_SHEET_ID);

(async function() {
    await doc.useServiceAccountAuth({
        // env var values are copied from service account credentials generated by google
        // see "Authentication" section in docs for more info
        client_email: REACT_APP_GOOGLE_CLIENT_EMAIL,
        private_key: REACT_APP_GOOGLE_PRIVATE_KEY.replace(/\\n/g, '\n'),
      });
}())

export default function Home() {
  const [playerRows, setPlayerRows] = useState([]);
  const [sheet, setSheet] = useState([]);

  const loadSheet = async (getRows) => {
    await doc.loadInfo()
              .then(() => {
                setSheet(doc.sheetsByIndex[0])
              })
              .then(async () => {
                const rows = await doc.sheetsByIndex[0].getRows()
                setPlayerRows(rows)
              })
  }

  useEffect(() => {
    loadSheet()
  }, [])

    return (
        <div>
            <h1>Gronert's Horseshoe</h1>
            <button onClick={() => openNetlifyModal()}>Login/Sign Up</button>
            <Table celled fixed singleLine>
                <Table.Header>
                    <Table.Row>
                        <Table.HeaderCell>Player Name</Table.HeaderCell>
                        <Table.HeaderCell>Total Buy Ins</Table.HeaderCell>
                        <Table.HeaderCell>Total Winnings</Table.HeaderCell>
                        <Table.HeaderCell>+/-</Table.HeaderCell>  
                    </Table.Row>
                </Table.Header>
                <Table.Body>
                    {playerRows && playerRows.map((row) => {
                        return (
                            <PlayerCard playerName={row.playerName} totalBuyIns={row.buyIn} winnings={row.winnings}
                                        key={playerRows.indexOf(row)} />
                        )
                    })}
                </Table.Body>
            </Table>
        </div>
    )
}
