import React, {useEffect, useState} from 'react';
import EntryForm from '../components/EntryForm';
import PlayerCard from '../components/NewTournamentPlayerCard';
import { GoogleSpreadsheet } from 'google-spreadsheet';

const {REACT_APP_SHEET_ID} = process.env;
const {REACT_APP_GOOGLE_CLIENT_EMAIL} = process.env;
const {REACT_APP_GOOGLE_PRIVATE_KEY} = process.env;

const doc = new GoogleSpreadsheet(REACT_APP_SHEET_ID);

(async function() {
    await doc.useServiceAccountAuth({
        // env var values are copied from service account credentials generated by google
        // see "Authentication" section in docs for more info
        client_email: REACT_APP_GOOGLE_CLIENT_EMAIL,
        private_key: REACT_APP_GOOGLE_PRIVATE_KEY.replace(/\\n/g, '\n'),
      });
}())


export default function Scoreboard() {
    const [newTournamentName, setNewTournamentName] = useState('');
    const [tournamentName, setTournamentName] = useState('');
    const [currentSheet, setCurrentSheet] = useState({});
    const [currentRows, setCurrentRows] = useState([]);
    const [sheetNames, setSheetNames] = useState([]);
    const [tournamentPlayers, setTournamentPlayers] = useState([]);
    const [firstPlace, setFirstPlace] = useState('');
    const [secondPlace, setSecondPlace] = useState('');
    const [thirdPlace, setThirdPlace] = useState('');
    const [highHand, setHighHand] = useState('');
    const [totalPot, setTotalPot] = useState(0);


    const loadSheet = async () => {
        await doc.loadInfo()
    }

    // If newTournamentName is declared, create a new sheet in doc with newTournamentName as the title
    const createNewSheet = async (newTournamentName) => {
        if(newTournamentName !== '') {
            const newSheet = await doc.addSheet({ title: `${newTournamentName}`, headerValues: ['playerName', 'buyIn', 'winnings'] });
            setTournamentName(newTournamentName)
        } else {
            console.log('No tournament name entered.')
        }
    }
    // Used when adding a player to the tournament, adds a row entry to the sheet with name and buyin amount
    const addRow = async (pName, buyInAmount, winnings) => {
        const sheet = doc.sheetsByTitle[tournamentName];
        const newRow = await sheet.addRow({ playerName: pName, buyIn: buyInAmount, winnings: winnings });
        setCurrentSheet(sheet)
        getRows();
    }
    //Retrieves rows from selected tournament sheet
    const getRows = async () => {
        const rows = await doc.sheetsByTitle[tournamentName].getRows()
        setCurrentRows(rows)
        let tournamentPlayersArr = [];
        currentRows.map((row) => {
            tournamentPlayersArr.push(row.playerName)
        })
        setTournamentPlayers(tournamentPlayersArr)
    }

    const addRebuy = async (playerName) => {
        const sheet = doc.sheetsByTitle[tournamentName];
        const rows = await sheet.getRows();
        for (let i = 0; i < rows.length; i++) {
            if(rows[i].playerName === playerName) {
                rows[i].buyIn = Number(rows[i].buyIn) + 20
                console.log(rows[i].buyIn)
                await rows[i].save()
                getRows();
            }
        }
    }
    
    const removePlayer = async (playerName) => {
        const sheet = doc.sheetsByTitle[tournamentName];
        const rows = await sheet.getRows();
        for (let i = 0; i < rows.length; i++) {
            if(rows[i].playerName === playerName) {
                await rows[i].delete();
                getRows();
            }
        }
    }
    // Takes all sheet titles and sets state of sheetNames to an array of their titles
    const getAllSheetNames = () => {
        let i = 0;
        let sheetNameArr = [];
        while(doc.sheetsByIndex[i] !== undefined) {
            sheetNameArr.push(doc.sheetsByIndex[i].title)
            console.log(doc.sheetsByIndex[i].title)
            i++
        }
        setSheetNames(sheetNameArr)
    }

    const getTotalPot = async () => {
        const rows = await doc.sheetsByTitle[tournamentName].getRows()
        let pot=0;
        rows.map((row) => {
            pot += Number(row.buyIn);
        })
        setTotalPot(pot)
    }

    // Sets value selected in dropdown to tournamentName state
    function handleTournamentChange(event) {
            setTournamentName(event.target.value);
        }

    // Loads the doc and filled sheetNames with all names of sheets in the doc
    useEffect(() => {
        loadSheet().then(response => getAllSheetNames())
    }, [])

    //Console.logs tournamentName whenever it changes
    useEffect(() => {
        console.log('rerender?')
        if(tournamentName !== "" && tournamentName !== '--Select a Tournament--') {
            getTotalPot()
            getRows()
        }
    }, [tournamentName])

    return (
        <div>
            <input placeholder="MonthYear" onChange={(e) => setNewTournamentName(e.target.value)} />
            <button onClick={() => createNewSheet(newTournamentName)}>Create New Tourament</button>
            <select name="tournaments" value={tournamentName} onChange={(handleTournamentChange)}>
                <option>--Select a Tournament--</option>
                {sheetNames && sheetNames.map((sheet) => {
                    return (
                        <option value={sheet} key={sheet}>{sheet}</option>
                    )
                })}
            </select>
            <EntryForm addRow={addRow} />
            {tournamentName}
            <table>
                <thead>
                    <tr>
                        <th>Player Name</th>
                        <th>Total Buy Ins</th>
                        <th>Winnings</th>
                        <th></th>
                        <th></th>  
                    </tr>
                </thead>
                <tbody>
                    {currentRows && currentRows.map((row) => {
                        return (
                            <PlayerCard playerName={row.playerName} totalBuyIns={row.buyIn} winnings={row.winnings}
                                        addRebuy={addRebuy} removePlayer={removePlayer}
                                        key={currentRows.indexOf(row)} />
                        )
                    })}
                </tbody>
            </table>
            <button onClick={() => getRows()}>Get Rows</button>
            <p>Total Pot = {totalPot}</p>
            <select value={firstPlace} onChange={(e) => setFirstPlace(e.target.value)}>
                <option>--Select Player--</option>
                {currentRows && currentRows.map((row) => {
                    return (
                    <option value={row.playerName} key={row.playerName}>{row.playerName}</option>
                    )
                })}
            </select>
            <select value={secondPlace} onChange={(e) => setSecondPlace(e.target.value)}>
                <option>---Select Player---</option>
                    {currentRows && currentRows.map((row) => {
                        return (
                        <option value={row.playerName} key={row.playerName}>{row.playerName}</option>
                        )
                    })}
            </select>
            <select value={thirdPlace} onChange={(e) => setThirdPlace(e.target.value)}>
                <option>---Select Player---</option>
                    {currentRows && currentRows.map((row) => {
                        return (
                        <option value={row.playerName} key={row.playerName}>{row.playerName}</option>
                        )
                    })}
            </select>
            <select value={highHand} onChange={(e) => setHighHand(e.target.value)}>
                <option>---Select Player---</option>
                    {currentRows && currentRows.map((row) => {
                        return (
                        <option value={row.playerName} key={row.playerName}>{row.playerName}</option>
                        )
                    })}
            </select>
        </div>
    )
}
